# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=7)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
